# https://www.kaggle.com/datasets/wenruliu/adult-income-dataset

In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("adult.csv")
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [4]:
df.groupby('age')['hours-per-week'].agg(['mean', 'median', 'min', 'max', 'std'])

          mean  median  min  max        std
age
17   21.137815    20.0    4   50  10.052279
18   25.745940    24.0    2   72  11.599559
19   30.560304    30.0    2   99  11.986582
20   32.432165    35.0    2   84  11.586053
21   34.252737    40.0    1   98  11.656146
..         ...     ...  ...  ...        ...
86   40.000000    40.0   40   40        NaN
87    7.000000     3.0    2   16   7.810250
88   35.833333    40.0    5   50  15.625833
89   30.000000    30.0   20   40  14.142136
90   37.654545    40.0    4   99  18.967046

[74 rows x 5 columns]

In [17]:
df['education'].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [18]:

encoder = OneHotEncoder(sparse_output=False)

encoded_data = encoder.fit_transform(df[['education']])

encoder.get_feature_names_out(['education'])

array(['education_10th', 'education_11th', 'education_12th',
       'education_1st-4th', 'education_5th-6th', 'education_7th-8th',
       'education_9th', 'education_Assoc-acdm', 'education_Assoc-voc',
       'education_Bachelors', 'education_Doctorate', 'education_HS-grad',
       'education_Masters', 'education_Preschool',
       'education_Prof-school', 'education_Some-college'], dtype=object)

In [20]:
label_map = {label:i for i, label in enumerate(encoder.get_feature_names_out(['education']))}
label_map

{'education_10th': 0,
 'education_11th': 1,
 'education_12th': 2,
 'education_1st-4th': 3,
 'education_5th-6th': 4,
 'education_7th-8th': 5,
 'education_9th': 6,
 'education_Assoc-acdm': 7,
 'education_Assoc-voc': 8,
 'education_Bachelors': 9,
 'education_Doctorate': 10,
 'education_HS-grad': 11,
 'education_Masters': 12,
 'education_Preschool': 13,
 'education_Prof-school': 14,
 'education_Some-college': 15}

In [25]:
df = pd.read_csv("/content/13Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [26]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
species          0
dtype: int64

In [27]:
df.groupby(["species"])["SepalLengthCm"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

In [28]:
df.groupby(["species"])["SepalLengthCm"].median()

species
Iris-setosa        5.0
Iris-versicolor    5.9
Iris-virginica     6.5
Name: SepalLengthCm, dtype: float64

In [29]:
df.groupby(["species"])["SepalLengthCm"].quantile(0.25)

species
Iris-setosa        4.800
Iris-versicolor    5.600
Iris-virginica     6.225
Name: SepalLengthCm, dtype: float64

In [30]:
df.groupby(["species"])["SepalLengthCm"].quantile(0.5)

species
Iris-setosa        5.0
Iris-versicolor    5.9
Iris-virginica     6.5
Name: SepalLengthCm, dtype: float64

In [31]:

df.groupby(["species"])["SepalLengthCm"].quantile(0.75)

species
Iris-setosa        5.2
Iris-versicolor    6.3
Iris-virginica     6.9
Name: SepalLengthCm, dtype: float64

In [32]:

df.groupby(["species"])["SepalLengthCm"].std()

species
Iris-setosa        0.352490
Iris-versicolor    0.516171
Iris-virginica     0.635880
Name: SepalLengthCm, dtype: float64

In [33]:

df.groupby(["species"])["SepalLengthCm"].describe()

                 count   mean       std  min    25%  50%  75%  max
species
Iris-setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [35]:
unique_species = df['species'].unique()


mapping = {species: i for i, species in enumerate(unique_species)}
print("Mapping Key:", mapping)

Mapping Key: {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}